{% set provider = "Atlas" %}
{% set goname = "github.com/terraform-providers/terraform-provider-"+provider.lower() %}
{% set version = "0.1.1" %}

{% set name = goname.split('/')[-1] %}

{% set x4_plugin = name + '_v' + version + "_x4" %}

{% set sha256 = "9781f583b9ebdfc05137e09b9c8d871d3e741d21171b521ac1be25ca66f89adf" %}
{% set sha256_win64 = "760518254c69c79e0cfbe7e607e895b0079478a45cfc2af8f2cf757ca392d1d9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://{{ goname }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}


build:
  number: 1002
  script:
    - go build -v -o {{ target_gobin }}{{ x4_plugin }}{{ target_goexe }}

requirements:
  build:
    - {{ compiler('go') }} 1.13
  run:
    - terraform 0.12

test:
  requires:         # [win]
    - m2-bash       # [win]
    - m2-coreutils  # [win]

  commands:
    - bash -euf -c "echo 'provider \"{{ provider|lower }}\" { version=\"{{ version }}\" }' > init.tf"
 
    - terraform init
    # Tests that no plugins were downloaded
    - test -f .terraform/plugins/{{ target_goos }}_{{ target_goarch }}/lock.json
    - test ! -f .terraform/plugins/{{ target_goos }}_{{ target_goarch }}/{{ x4_plugin }}{{ target_goexe }}

about:
  home: https://www.terraform.io
  license: MPL-2.0
  summary: The Terraform Terraform Enterprise ({{ provider }}) provider
  doc_url: https://www.terraform.io/docs/providers/{{ provider|lower }}/index.html
  dev_url: https://github.com/terraform-providers/{{ name }}

extra:
  recipe-maintainers:
    - conda-forge/terraform
