appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Wj//6lA6Wv8ZOTwK8JJLQlr2hg2DQ900IjU1yTN3kR6oLbyvbmPbCxuKhZGGx9ekcDVxGfz/YXhfzEOaCqStV+PVLlhNxn0VUeGEIICb8p8NQKnJWT9ephYPezhKG6lJsgiY12y66PTPh3LOrtiHpVK2znY3sTecmPq8Vj0t1Lp73BM77ithR92fb8ZEpq4oQySoMJeSpCuavSPQuiPUuW1fq/ua32YG/R5TxvJpmVEliwcZeV+njTkSwXorsiri7x8KZyC9VNoahAJ4CCVbuMRG8YnBVLU/Moj+3w7GxvDZ1BG+s32hvc/MoHplaWNf2XKCuUXkY3LdWAhr7RwYIhIS46MQQLty2FrByddoHLSlv6ALlp0yXSoAMppHv1L3TZY19IEvXHJj10GBcx20Yl6reeIt7s6gHG+dfsmTQpsR6OO0h2Oh+ONuPyk/kTwJPuDIRhUcO4eU7whc7D1tetzPurO4VGzkzZB/jnPcEV4cb+tz9QIWXypvkNbovvxHdAS7agO+24jv1ecRcFueU2ImtR5isib6p7lqEoEdn41OYfAg7gNob3NF2JUyUTg6/IoxRKRDYtQcOflwTQglCi24bQ1PoS6ZIBWUq3py+pAazscBjR5I+UZPM4soYHygdErjVqQ7CTFZkaRQiPZWwPFUvaqE73A9e4QExy2uwvM=}
provider:
  win: azure
